### ISSUE TITLE
[Bug]: 遇到几个问题

### ISSUE THREAD

**Issue by lemon4ex** [deatil/lakego-admin-frontend#10]
### lakego-admin 版本

最新master分支，v1.1.0? 

### Golang 版本

go version go1.21.3 darwin/amd64

### 是否依旧存在

可以

### bug描述

1. 登录页出现验证码获取失败提示时，点击确认无任何反应
2. 登录后，点击本地拓展，点击实例拓展的安装按钮，弹出安装提示，这里点击取消无任何反应 
3. 登录后，点击 权限管理->用户组->用户组树，进入用户组树页面，进入这个页面后，点击已经打开的其他TAB页都会变成一片空白，必须刷新才能正常，另外，点击添加路由，出现的窗口，标题不对，显示的是添加用户

**Comment by lemon4ex** [comment]
是最新的vue和 ant design 兼容问题，经测试，固定vue版本为3.2.20可解决对话框无法关闭的问题，参考文章：https://blog.csdn.net/weixin_43417844/article/details/135679893

**Comment by deatil** [comment]
1和2是vue是兼容性问题，暂时不处理，给了个提示。
3问题已经修复了。
