### ISSUE TITLE
[Question]: yarn build  error 

### ISSUE THREAD

**Issue by SnoW-Wei** [deatil/lakego-admin-frontend#3]
### 疑惑的地方

encountered this problem 。

![image](https://user-images.githubusercontent.com/4156995/203747701-03ee4eba-5a6a-4979-8fcf-703a77d6d913.png)

### 期望的结果

I want to know why

**Comment by deatil** [comment]
https://github.com/deatil/lakego-admin-frontend/blob/1915e9b51b0e023e5151817a7d75ef44aa8ffc1d/.env.production#L2 need set false. admin mock dir is deleted.

**Comment by SnoW-Wei** [comment]
![image](https://user-images.githubusercontent.com/4156995/203751515-ac9ca3c4-2b17-40d2-811d-06d65717d5f2.png)

these dir  were also deleted。  

I just do this , it's worked 

![image](https://user-images.githubusercontent.com/4156995/203752303-0128292e-e337-44ac-86e1-146c79c36c0b.png)

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/4156995/203751515-ac9ca3c4-2b17-40d2-811d-06d65717d5f2.png)
> 
> these dir were also deleted。
> 
> I just do this , it's worked
> 
> ![image](https://user-images.githubusercontent.com/4156995/203752303-0128292e-e337-44ac-86e1-146c79c36c0b.png)

yes. the need change.
