### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by white0dew** [deatil/lakego-admin-frontend#4]
### lakego-admin 版本

1.0.1

### Golang 版本

vue

### 是否依旧存在

可以

### bug描述

when i run “yarn dev”，i got this：
 YN0001: │ Error: bin-wrapper@npm:^4.0.0: No candidates found
    at ge (C:\Users\13736\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7784)
    at runMicrotasks (<anonymous>)

how should i do？

**Comment by deatil** [comment]
now the project run base on node v16.6.2 / npm 6.14.8. you can see your npm version

**Comment by deatil** [comment]
yarn version see what it is not match.

**Comment by deatil** [comment]
yarn version see what it is not match.
