### ISSUE TITLE
[Feature]: 拉取前后端代码运行，只有控制台和图标

### ISSUE THREAD

**Issue by tianheyi** [deatil/lakego-admin-frontend#7]
### 功能描述以及必要性描述

前端版本 1.0.3
后端版本 LakegoAdmin v1.2.2

你好，我在按照README.md初始化启动前后端项目后，登陆admin进入前端页面只有控制台和图标，没有账号和权限管理等相关入口，我看前后端中有这部分代码，但是前端好像没有被引用，是需要自己手动去调用吗，不太懂前端。
![图片展示](https://github.com/tianheyi/resource-images/blob/main/Snipaste_2023-09-20_08-59-26.png)

### 建议和方案

前端代码直接引入这部分代码

**Comment by deatil** [comment]
左侧的菜单是需要导入权限后才会显示的。安装后默认是没有菜单数据的，需要执行脚本后导入菜单数据才行
