### ISSUE TITLE
[Feature]: 考虑加个菜单功能吗

### ISSUE THREAD

**Issue by tianheyi** [deatil/lakego-admin-frontend#8]
### 功能描述以及必要性描述

1. 菜单功能类似[go-admin-team/go-admin](https://gitee.com/go-admin-team/go-admin?_from=gitee_search)或者[go-admin/go-admin](https://gitee.com/go-admin/go-admin?_from=gitee_search)那种在前端就能操作菜单的功能

**Comment by deatil** [comment]
现阶段暂时保持，后面有合适的方法就会加上
