### ISSUE TITLE
[Question]: 部署项目后验证码无法加载出来，无法进行登录

### ISSUE THREAD

**Issue by zhutiancheng1997** [deatil/lakego-admin-frontend#9]
### 疑惑的地方

部署项目后验证码无法加载出来，无法进行登录，请问应该怎么解决呢？

<img width="1448" alt="image" src="https://github.com/deatil/lakego-admin-frontend/assets/14163276/6fc3efe1-3626-44fb-a538-4b7793eca89a">

### 期望的结果

无

**Comment by deatil** [comment]
打包部署对应的env的base_url需要设置为部署的对象域名，设置后再打包
可以先在控制台看下请求的域名是什么

**Comment by zhutiancheng1997** [comment]
不好意思，我前端不是很懂，请问你说的base_url是.env文件里的VITE_GLOB_API_URL和VITE_GLOB_UPLOAD_URL这两个属性吗？

**Comment by deatil** [comment]
> 不好意思，我前端不是很懂，请问你说的base_url是.env文件里的VITE_GLOB_API_URL和VITE_GLOB_UPLOAD_URL这两个属性吗？

是的。前端打包为部署的时候，另外两个.env开头的需要改为正式的域名

**Comment by zhutiancheng1997** [comment]
感谢大佬，我按照你说的方式进行了修改，但是我发现请求还是会失败，我修改env文件里用的默认8080端口，但是console里打印无法请求，然后我去容器里排查，lsof -i:8080并没有对应进程启动，这是为什么呢？
其中一个配置：VITE_GLOB_UPLOAD_URL=http://xxxx:8080/admin-api/upload/file

**Comment by deatil** [comment]
容器？你后端项目是和前端部署在一个容器吗？
